---
apiVersion: helm.sh/v1beta1
kind: Lifecycle
metadata:
  name: canary
spec:
  # The eventKey will be the value of the `helm-lifecycle-event` label for the
  # LifecycleEvent. The controller that handles this should filter events based
  # on this key
  eventKey: canary
---
apiVersion: helm.sh/v1beta1
kind: Lifecycle
metadata:
  name: blue-green
spec:
  eventKey: bluegreen
---
apiVersion: helm.sh/v1beta1
kind: Lifecycle
metadata:
  # A Lifecycle that would take the place of pre-* hooks in Helm 2
  name: pre-deploy
spec:
  eventKey: predeploy
---
apiVersion: helm.sh/v1beta1
kind: Lifecycle
metadata:
  # A Lifecycle that would take the place of post-* hooks in Helm 2
  name: post-deploy
spec:
  eventKey: postdeploy
---
apiVersion: helm.sh/v1beta1
kind: Lifecycle
metadata:
  # A Lifecycle that would replace the current `--wait` functionality in Helm 2
  # and would ensure that all created resources are ready, bound, etc.
  name: running
spec:
  eventKey: running
